### ISSUE TITLE
Add an option to track request

### ISSUE THREAD

**Issue by dvidsilva** [TechForPR/chefsForPR#25]
Currently the track request button doesn't do anything, it can probably change so that there's an input and you add the code in the input and then press the button and get redirected to `/request/:shortId`

**Comment by apravink** [comment]
I would like to work on this!

**Comment by dvidsilva** [comment]
@apravink   I sent you an invite to the organization so you can be assigned and push to the repo. Let me know if you need help and if you can sort out #29 

Thanks !

**Comment by apravink** [comment]
Thanks @dvidsilva . I'll upgrade my Node version and give it a shot first.

**Comment by dvidsilva** [comment]
Hey, going to add this in a sec, but let me know and we can assign you a differnet one. Are you in the slack?

**Comment by apravink** [comment]
Oh okay. No not on slack, could you pass me the url?

On Oct 16, 2017 3:04 PM, "Dvid Silva" <notifications@github.com> wrote:

Hey, going to add this in a sec, but let me know and we can assign you a
differnet one. Are you in the slack?

—
You are receiving this because you were assigned.

Reply to this email directly, view it on GitHub
<https://github.com/TechForPR/chefsForPR/issues/25#issuecomment-336998381>,
or mute the thread

**Comment by dvidsilva** [comment]
Send me your email, or request an invite here: http://techqueria.org/slack
